export const en = {
    post: 'Post',
    noposts: 'None',
    editorpost: 'Edit',
    searchpost: 'Search post',
    postdetailed: 'Detail',
    title: 'Title',
    describe: 'Describe',
    content: 'Content',

    publish: 'Publish',
    productpublish: 'Publish For Product',
    selectproduct: 'Select Product',
    ordinarypublish: 'Publish Fro Ordinary',
    noproduct: "No Product",


    sales: 'Internal Sales',
    agent: 'ight Agent',
    privateSite: 'Private Site',
    publicSite: 'Public Site',
    internationSite: 'Internation Site',

    sourcecode: 'Code',
    picture: 'Picture',
    searchpicture: 'Search picture',
    selectpicture: 'Select picture',
    editorpicture: 'Editor picture',
    nopicture: 'No picture',
    uploadpicture: 'Upload picture',
    uploadfile: 'Upload audio',

    template: 'Template',
    selecttemplate: 'Select template',
    notemplate: 'No template',
    preview: 'Preview',

    page: 'Page',
    name: 'Name',
    editorpage: 'Editor page',
    sort: 'Sort',
    module: 'Mdule',
    editorsubmodule: 'Editor Sub module',
    mymodule: 'My module',

    me: 'Me',
    tag: 'Tag',
    set: 'Set',
    logout: 'Logout',
    about: 'About',
    password: 'Password',
    account: 'Account',
    version: 'Version',
    privacypolicy: 'Privacy policy',
    personalinformation: 'Personal information',
    headportrait: 'Head Portrait',

    all: 'All',
    submit: 'Submit',
    select: 'Select',
    save: 'Save',
    copy: 'Copy',
    copysuccess: 'Copy Success',
    editor: 'Editor',
    pleaseselect: 'Please select',

    veryimport: 'Very Import',
    general: 'General'
}

export const zh = {

    post: '帖文',
    noposts: '无帖文',
    editorpost: '编辑帖文',
    searchpost: '搜索帖文',
    postdetailed: '帖文明细',
    title: '标题',
    describe: '描述',
    content: '内容',
    estimate: '评价',
    publish: '发布',
    productpublish: '产品发布',
    selectproduct: '选择产品',
    ordinarypublish: '普通发布',
    noproduct: "无产品",

    sales: '销售助手',
    agent: '轻代理',
    privateSite: '内部网页',
    publicSite: '内容网站',
    internationSite: '国际网站',

    sourcecode: '源码',

    picture: '图片',
    searchpicture: '搜索图片',
    selectpicture: '选择图片',
    editorpicture: '编辑图片',
    nopicture: '无图片',
    uploadpicture: '上传图片',
    uploadaudio: '上传音频',

    template: '模板',
    selecttemplate: '选择模板',
    notemplate: '无模板',
    preview: '预览',
    link: '链接',

    page: '网页',
    name: '名称',
    editorpage: '编辑网页',
    sort: '排序',
    module: '模块',
    editorsubmodule: '编辑模块',
    mymodule: '我的模块',

    me: '我的',
    tag: '标签',
    set: '设置',
    team: '团队',
    myteam: '我的团队',
    privatedetail: '个人明细',
    logout: '退出登陆',
    about: '关于',
    password: '密码',
    account: '账户信息',
    version: 'Version',
    privacypolicy: '隐私政策',
    personalinformation: '个人信息',
    headportrait: '头像',

    all: '全部',
    submit: '提交',
    select: '选择',
    save: '保存',
    copy: '复制',
    copysuccess: '复制成功',
    editor: '编辑',
    pleaseselect: '请选择',

    timepublish: "时间发布",

    veryimport: "重要",
    general: "普通"
}